#!/usr/bin/env ruby

require 'eventmachine'
require 'evma_httpserver'

load "server/Client.rb"
load "server/WSClient.rb"

puts "Launching server"

def exitServer exitType
  printf "\r"
  Client.clients.each do |client|
    client.exit exitType
  end
  EM.stop_event_loop if exitType == :signalCatch
  begin
    $railsPID = File.new("ui/webclient/tmp/pids/server.pid").read.to_i
  rescue Errno::ENOENT
    $railsPID = -42
  end
  Process.kill "INT", $railsPID if $railsPID > 1
  puts "Terminating server"
  exit 0
end

launchRails = true              # Set to false with options

opts = {
  :host => "0.0.0.0",
  :port => 8080,
  :wshost => "0.0.0.0",
  :wsport => 8081,
  :railshost => "0.0.0.0",
  :railsport => 3000
}

opts[:port] = ARGV[0].to_i if ARGV[0]
opts[:wsport] = opts[:port] + 1

Signal.trap "INT" do
  exitServer :signalCatch
end

Signal.trap "TERM" do
  exitServer :signalCatch
end

if launchRails
  Process.fork do
    Dir.chdir "ui/webclient"
    puts "Executing rails server -d -b #{opts[:railshost]} -p #{opts[:railsport]}"
    Process.exec "rails server -d -b #{opts[:railshost]} -p #{opts[:railsport]}"
  end
end

begin
  EM.run do
    EM.start_server opts[:host], opts[:port], Client
    EM.start_server(opts[:wshost], opts[:wsport], WSClient,
                    :host => opts[:wshost],
                    :port => opts[:wsport])
  end
rescue Interrupt
  puts "\rOn operating systems where Signal.trap doesn't work,"
  puts "catch Interrupt works."
  exitServer :exceptionCatch
end
