#!/usr/bin/env ruby

#
# Class to stock the diff made by Diff::LCS.diff
#
module Mine
  class Change
    attr_reader :cursorBefore, :cursorAfter, :user, :diff

    #
    # constructor taking the user who made the change, the position of the cursor before and after the change and the diff generated by the gem Diff-LCS
    #
    def initialize user, cursorBefore, cursorAfter, diff
      @diff = diff[0]
      @user = user
      @cursorBefore = cursorBefore
      @cursorAfter = cursorAfter
    end

    #
    # build the SYNC request
    #
    def to_request bufferId
      reqargs = {
        "buffer" => bufferId,
        "user" => @user.userInfo.name,
        "cursorBefore" => @cursorBefore,
        "cursorAfter" => @cursorAfter,
        "diff" => @diff.to_a
      }
      "SYNC=#{JSON.dump reqargs}"
    end
  end
end
